global:
  scrape_interval:     15s

scrape_configs:

  - job_name: applications
    scrape_interval: 5s
    metrics_path: "/admin/prometheus"
    static_configs:
      - targets:
        - contract-service-jvm-tomcat:8080
        - contract-service-native-tomcat:8080
        - contract-service-liberica-tomcat:8080
        - contract-service-liberica-netty:8080
        - contract-service-native-ee-g1-tomcat:8080
        - contract-service-native-ee-g1-pgo-tomcat:8080
        - contract-service-native-ee-g1-reactive:8080
        - contract-service-native-ee-serial-reactive:8080
        - contract-service-native-ee-serial-pgo-reactive:8080
        - contract-service-native-netty:8080
        - contract-service-jvm-netty: 8080s

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - cadvisor:8080
    metric_relabel_configs:
      - source_labels: [ id ]
        action: keep
        regex: '/docker/(.*)'

      - source_labels: [container_label_com_docker_compose_service]
        target_label: docker_compose_service

      - regex: container_.*|image
        action: labeldrop
