version: "2"

services:
  mongo:
    image: mongo:4.2.7
    mem_limit: 64m
    expose:
      - "27017"
    networks:
      backend:
        aliases:
          - mongo-service

  contract-app:
    image: eshishkin/demo/spring-native/tiny
    mem_limit: 650m
    expose:
      - "8080"
    ports:
      - "18080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx128m -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=128M -XX:+UseContainerSupport -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service

networks:
  backend:
