version: "2"

services:
  mongo:
    image: mongo:4.2.7
    mem_limit: 300m
    cpus: 0.5
    expose:
      - "27017"
    volumes:
      - ./mongo/startup.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      backend:
        aliases:
          - mongo-service

  app-jvm-tomcat:
    image: eshishkin/demo/spring-native/jvm-blocking
    mem_limit: 650m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xss512k -Xmx128m -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=60M -XX:+UseContainerSupport -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch
    command: [
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-jvm-tomcat

  app-native-tomcat:
    image: eshishkin/demo/spring-native/tiny-blocking
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18081:8080"
    command: [
      "-Xms128m",
      "-Xmx128m",
      "-Xss512k",
#      "-XX:+PrintGC",
#      "-XX:+PrintGCSummary",
#      "-XX:+PrintGCTimeStamps",
#      "-XX:+VerboseGC",
      "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-tomcat

  app-liberica-tomcat:
    image: eshishkin/demo/spring-native/liberica-nik-blocking
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18082:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
#      "-XX:+PrintGC",
#      "-XX:+PrintGCSummary",
#      "-XX:+PrintGCTimeStamps",
#      "-XX:+VerboseGC",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-liberica-tomcat

  app-native-ee-g1-tomcat:
    image: eshishkin/demo/spring-native/enterprise-g1
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18083:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-ee-g1-tomcat

  app-native-ee-g1-pgo-tomcat:
    image: eshishkin/demo/spring-native/enterprise-g1-pgo
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18084:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-ee-g1-pgo-tomcat

  app-native-ee-g1-reactive:
    image: eshishkin/demo/spring-native/enterprise-g1-netty
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18085:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-ee-g1-reactive

  app-native-ee-serial-reactive:
    image: eshishkin/demo/spring-native/enterprise-serial-netty
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18087:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-ee-serial-reactive

  app-native-ee-serial-reactive-pgo:
    image: eshishkin/demo/spring-native/enterprise-serial-netty-pgo
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18088:8080"
    volumes:
      - ./data/pgo-serial-reactive/:/app
#      - ./data/profile-serial.iprof/:/app
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-ee-serial-pgo-reactive

  app-native-netty:
    image: eshishkin/demo/spring-native/tiny-reactive
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18089:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
      #      "-XX:+PrintGC",
      #      "-XX:+PrintGCSummary",
      #      "-XX:+PrintGCTimeStamps",
      #      "-XX:+VerboseGC",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-native-netty

  app-liberica-netty:
    image: eshishkin/demo/spring-native/liberica-nik-netty
    mem_limit: 250m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18091:8080"
    command: [
        "-Xms128m",
        "-Xmx128m",
        "-Xss512k",
      #      "-XX:+PrintGC",
      #      "-XX:+PrintGCSummary",
      #      "-XX:+PrintGCTimeStamps",
      #      "-XX:+VerboseGC",
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-liberica-netty

  app-jvm-netty:
    image: eshishkin/demo/spring-native/jvm-reactive
    mem_limit: 650m
    cpus: 1
    expose:
      - "8080"
    ports:
      - "18090:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xss512k -Xmx128m -XX:MaxMetaspaceSize=100M -XX:ReservedCodeCacheSize=60M -XX:+UseContainerSupport -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch
    command: [
        "--spring.data.mongodb.uri=mongodb://mongo-service:27017",
    ]
    depends_on:
      - mongo
    networks:
      backend:
        aliases:
          - contract-service-jvm-netty

  prometheus:
    image: prom/prometheus:latest
    cpus: 0.15
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus/data
    command: "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      backend:
        aliases:
          - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    cpus: 0.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command: [
        '--housekeeping_interval=1s',
        '-docker_only=true'
    ]
    networks:
      - backend

  grafana:
    image: grafana/grafana:7.1.5
    cpus: 0.15
    ports:
      - 3000:3000
    command: "--config=/etc/grafana/custom/custom.ini"
    depends_on:
      - cadvisor
      - prometheus
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/settings:/etc/grafana/custom
    networks:
      - backend

networks:
  backend:
